In [1]:
import pandas as pd
import numpy as np
import json
import seaborn as sns
import matplotlib.pyplot as plt

# Warning off
pd.options.mode.chained_assignment = None

import warnings
warnings.filterwarnings("ignore")

In [7]:
def process_filtered_df(results_df,df_def,defense,narcissus,header=None,header_idx=0):
    if narcissus:
        avg_poison_success = df_def['P1 Acc'].mean() * 100
        std_poison_success = df_def['P1 Acc'].std() * 100
        avg_nat_acc = df_def['End Acc'].mean()
        std_nat_acc = df_def['End Acc'].std()
        max_poison_success = df_def['P1 Acc'].max() * 100


        if header is None:
            results_df.loc[defense, 'Avg Poison Success'] = f'{avg_poison_success:.2f}\u00B1{std_poison_success:.1f}'
            results_df.loc[defense,'Avg Nat Acc'] = f'{avg_nat_acc:.2f}\u00B1{std_nat_acc:.2f}'
            results_df.loc[defense,  'Max Poison Success'] = f'{max_poison_success:.2f}'

        else:
            results_df.loc[defense, (header_idx, 'Avg Poison Success')] = f'{avg_poison_success:.2%}\u00B1{std_poison_success:.1f}'
            results_df.loc[defense, (header_idx, 'Avg Nat Acc')] = f'{avg_nat_acc:.2f}\u00B1{std_nat_acc:.1f}'
            results_df.loc[defense, (header_idx, 'Max Poison Success')] = f'{max_poison_success:.2f}'

    else:

        success_rate = (df_def["Success"] == True).sum() / len(df_def)
        avg_nat_acc = df_def["End Acc"].mean()
        std_nat_acc = df_def["End Acc"].std()

        if header is None:
            results_df.loc[defense, 'Poison Success'] = f'{success_rate:.2%}'
            results_df.loc[defense, 'Natural Accuracy'] = f'{avg_nat_acc:.2f}%\u00B1{std_nat_acc:.1f}'

        else:
            results_df.loc[defense, (header_idx, 'Poison Success')] = f'{success_rate:.2%}'
            results_df.loc[defense, (header_idx, 'Natural Accuracy')] = f'{avg_nat_acc:.2f}%\u00B1{std_nat_acc:.1f}'

def export_results(df, narcissus = False, header=None, filters = {}):

    # Iterate through the filters
    for key, value in filters.items():
        df = df[df[key] == value]

    # Initialize an empty DataFrame for results
    if narcissus:
        if header is None:
            columns = ['Avg Poison Success', 'Avg Nat Acc','Max Poison Success']
        else:
            columns = pd.MultiIndex.from_product([np.sort(df[header].unique()), ['Avg Poison Success', 'Avg Nat Acc','Max Poison Success']],
                                     names=[header, 'Metric'])

    else:
        if header is None:
            columns = ['Poison Success', 'Natural Accuracy']
        else:
            columns = pd.MultiIndex.from_product([df[header].unique(), ['Poison Success', 'Natural Accuracy']],
                                                names=[header, 'Metric'])

    # Define the defenses
    defenses = ['None', 'EBM','Diff','EBM_Diff']                                         
    
    # Populate the DataFrame
    results_df = pd.DataFrame(columns=columns)

    if header is None: header_idxs = [0]
    else: header_idxs = df[header].unique()

    for header_idx in header_idxs:

        for defense in defenses:
            if header is None:
                if defense == 'Diff':
                    for steps in np.sort(df['Steps'].unique()):
                        df_def = df[(df['Defense'] == defense) & (df['Steps'] == steps)]
                        process_filtered_df(results_df,df_def,defense+f'-{steps}',narcissus,header,header_idx)
                        print(f'Added {defense}-{steps} to results_df with num rows {len(df_def)}')
                elif defense == 'EBM_Diff':
                    for steps in np.sort(df['Steps'].unique()):
                        df_def = df[(df['Defense'] == defense) & (df['Steps'] == steps)]
                        process_filtered_df(results_df,df_def,defense+f'-{steps}',narcissus,header,header_idx)
                        print(f'Added {defense}-{steps} to results_df with num rows {len(df_def)}')
                else:
                    df_def = df[(df['Defense'] == defense)]
                    process_filtered_df(results_df,df_def,defense,narcissus,header,header_idx)
                    print(f'Added {defense} to results_df with num rows {len(df_def)}')

            else:
                df_def = df[(df['Defense'] == 'None') & (df[header] == header_idx)]
                process_filtered_df(results_df,df_def,defense,narcissus,header,header_idx)

    return results_df

In [3]:
df = pd.read_csv('/home/sunaybhat/results_EBM_Defense/From_Scratch/Narcissus/Results.csv')

df['Defense'] = df['Defense'].fillna('None')
df['Steps'] = df['subset_size'] = df['Args'].apply(lambda x: json.loads(x)['diff_steps'] if 'diff_steps' in x else np.nan)
df['Steps'] = df['Steps'].fillna(125)


columns = ['Avg Poison Success', 'Avg Nat Acc','Max Poison Success']
results_df = pd.DataFrame(columns=columns)
for steps in np.sort(df['Steps'].unique()):
    df_def = df[(df['Defense'] == defense) & (df['Steps'] == steps)]
    process_filtered_df(results_df,df_def,defense+f'-{steps}',True)
    print(f'Added {defense}-{steps} to results_df with num rows {len(df_def)}')
df_results = export_results(df,narcissus=True)

df_results

Added None to results_df with num rows 10
Added EBM to results_df with num rows 10
Added Diff-10.0 to results_df with num rows 10
Added Diff-25.0 to results_df with num rows 10
Added Diff-50.0 to results_df with num rows 10
Added Diff-100.0 to results_df with num rows 10
Added Diff-125.0 to results_df with num rows 10
Added Diff-150.0 to results_df with num rows 10
Added Diff-175.0 to results_df with num rows 10
Added Diff-200.0 to results_df with num rows 8
Added EBM_Diff-10.0 to results_df with num rows 10
Added EBM_Diff-25.0 to results_df with num rows 10
Added EBM_Diff-50.0 to results_df with num rows 10
Added EBM_Diff-100.0 to results_df with num rows 10
Added EBM_Diff-125.0 to results_df with num rows 10
Added EBM_Diff-150.0 to results_df with num rows 10
Added EBM_Diff-175.0 to results_df with num rows 10
Added EBM_Diff-200.0 to results_df with num rows 0

               Avg Poison Success Avg Nat Acc Max Poison Success
None                   43.95±33.6  94.89±0.23              93.59
EBM                      1.34±0.6  92.73±0.22               2.29
Diff-10.0              42.63±47.5  94.42±0.13              99.76
Diff-25.0              42.08±48.6  94.04±0.16              99.99
Diff-50.0              22.66±39.8  93.67±0.13              99.86
Diff-100.0               2.36±2.4  93.64±0.13               8.92
Diff-125.0               2.00±2.0  93.50±0.16               7.49
Diff-150.0               1.96±1.9  93.36±0.23               7.16
Diff-175.0               1.72±1.4  93.24±0.26               5.42
Diff-200.0               1.52±0.9  93.27±0.27               3.69
EBM_Diff-10.0            1.81±1.3  93.06±0.14               4.56
EBM_Diff-25.0            1.80±1.3  92.79±0.30               4.91
EBM_Diff-50.0            1.95±1.7  92.59±0.36               6.38
EBM_Diff-100.0           1.79±1.4  92.43±0.17               5.47
EBM_Diff-125.0           1.75±1.3  92.38±0.26               5.19
EBM_Diff-150.0           1.63±1.1  92.28±0.21               4.24
EBM_Diff-175.0           1.55±0.9  92.06±0.18               3.64
EBM_Diff-200.0            nan±nan     nan±nan                nan

In [12]:
df = pd.read_csv('/Users/sunaybhat/Desktop/Results_yuan.csv')

df['Defense'] = df['Defense'].fillna('None')
df['Steps'] = df['Args'].apply(lambda x: json.loads(x)['num_t_steps'] if 'num_t_steps' in x else np.nan)
df['EBM'] = df['Args'].apply(lambda x: json.loads(x)['ebm_type'] if 'ebm_type' in x else np.nan)

columns = ['Avg Poison Success', 'Avg Nat Acc','Max Poison Success']
results_df = pd.DataFrame(columns=columns)
for ebm in np.sort(df['EBM'].unique()):
    for steps in np.sort(df['Steps'].unique()):
        df_def = df[(df['EBM'] == ebm) & (df['Steps'] == steps)]
        process_filtered_df(results_df,df_def,f'{ebm}-{steps}',True)
        print(f'Added {ebm}-{steps} to results_df with num rows {len(df_def)}')

results_df

Added EBMSNGAN32-1000 to results_df with num rows 30
Added EBM_Small-1000 to results_df with num rows 10

                Avg Poison Success Avg Nat Acc Max Poison Success
EBMSNGAN32-1000           1.29±0.7  92.91±0.16               2.73
EBM_Small-1000            1.29±0.5  92.94±0.23               2.35

In [9]:
df

,Defense,Target Index,End Acc,P1 Acc,T1 Acc,Exp Name,Calc Time,Train Time,P2 Acc,T2 Acc,P3 Acc,T3 Acc,Args,Logs,Steps,subset_size,EBM
0,EBM_Diff,7,92.85,0.007724,0.917760,narcissus8-sebmdiff150,2024_02_22_19_26,5505.106470,0.011906,0.879005,0.018178,0.780942,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [2.1766599947229373, 1.53499831...",NaN,NaN,EBM_Small
1,EBM_Diff,3,92.80,0.023548,0.931272,narcissus8-sebmdiff150,2024_02_22_19_26,5381.913307,0.048746,0.884441,0.094586,0.792738,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.995302487517257, 1.471154875...",NaN,NaN,EBM_Small
2,EBM_Diff,6,92.85,0.018178,0.903059,narcissus8-sebmdiff150,2024_02_22_19_26,5383.489468,0.144564,0.731272,0.336620,0.460101,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [2.113432114691381, 1.619658673...",NaN,NaN,EBM_Small
3,EBM_Diff,5,92.94,0.014877,0.930062,narcissus8-sebmdiff150,2024_02_22_19_26,5509.982319,0.024890,0.895004,0.037676,0.818310,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9586646925762792, 1.41083328...",NaN,NaN,EBM_Small
4,EBM_Diff,4,93.06,0.013996,0.919586,narcissus8-sebmdiff150,2024_02_22_19_26,5512.270754,0.065405,0.838886,0.150022,0.679643,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9061439101348447, 1.32399762...",NaN,NaN,EBM_Small
5,EBM_Diff,1,93.04,0.007923,0.911334,narcissus8-sebmdiff150,2024_02_22_19_26,5474.408305,0.023460,0.827245,0.074428,0.637148,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9215604103434727, 1.41344956...",NaN,NaN,EBM_Small
6,EBM_Diff,2,92.49,0.014085,0.921501,narcissus8-sebmdiff150,2024_02_22_19_26,5509.285694,0.043398,0.866285,0.100836,0.733319,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [2.065028467751525, 1.483485010...",NaN,NaN,EBM_Small
7,EBM_Diff,0,93.39,0.013226,0.918090,narcissus8-sebmdiff150,2024_02_22_19_26,5373.882038,0.028873,0.848151,0.077883,0.705942,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [2.0185581884725625, 1.46464156...",NaN,NaN,EBM_Small
8,EBM_Diff,9,92.97,0.008473,0.914283,narcissus8-sebmdiff150,2024_02_23_05_24,4927.839193,0.040273,0.801100,0.079467,0.592033,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.875944793071893, 1.356907082...",NaN,NaN,EBM_Small
9,EBM_Diff,8,93.03,0.006712,0.915933,narcissus8-sebmdiff150,2024_02_23_05_24,4808.195618,0.016417,0.850352,0.038974,0.713930,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8572408915175806, 1.32202747...",NaN,NaN,EBM_Small
10,EBM_Diff,7,92.86,0.004952,0.922205,narcissus8-ebm50diffmcmc150,2024_02_23_19_34,5445.716496,0.008605,0.890823,0.014437,0.805964,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8561691061005263, 1.39369443...",NaN,NaN,EBMSNGAN32
11,EBM_Diff,3,93.06,0.020797,0.932813,narcissus8-ebm50diffmcmc150,2024_02_23_19_34,5443.275585,0.041505,0.893684,0.080480,0.807130,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [2.0411592840843493, 1.46230527...",NaN,NaN,EBMSNGAN32
12,EBM_Diff,6,92.61,0.027333,0.889723,narcissus8-ebm50diffmcmc150,2024_02_23_19_34,5434.149748,0.217011,0.668662,0.434969,0.379247,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.953790441498427, 1.481102810...",NaN,NaN,EBMSNGAN32
13,EBM_Diff,5,93.15,0.020048,0.928829,narcissus8-ebm50diffmcmc150,2024_02_23_19_34,5432.426916,0.034463,0.887808,0.052179,0.810101,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.7948531784364938, 1.32483318...",NaN,NaN,EBMSNGAN32
14,EBM_Diff,4,92.95,0.013908,0.914040,narcissus8-ebm50diffmcmc150,2024_02_23_19_34,5440.282167,0.047271,0.842826,0.106008,0.703389,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8794105202340714, 1.39079429...",NaN,NaN,EBMSNGAN32
15,EBM_Diff,1,92.73,0.006602,0.914305,narcissus8-ebm50diffmcmc150,2024_02_23_19_34,5443.179044,0.019498,0.841637,0.082680,0.649384,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8835471023988846, 1.29019427...",NaN,NaN,EBMSNGAN32
16,EBM_Diff,2,92.95,0.015075,0.924362,narcissus8-ebm50diffmcmc150,2024_02_23_19_34,5436.312951,0.056514,0.862764,0.154930,0.725748,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [2.0748258124836876, 1.49778968...",NaN,NaN,EBMSNGAN32
17,EBM_Diff,0,92.84,0.010805,0.911752,narcissus8-ebm50diffmcmc150,2024_02_23_19_34,5439.186850,0.020841,0.849318,0.052311,0.732835,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9035528221398668, 1.34548740...",NaN,NaN,EBMSNGAN32
18,EBM_Diff,9,92.99,0.007702,0.915955,narcissus8-ebm50diffmcmc150,2024_02_23_22_18,4951.470445,0.025088,0.842936,0.094762,0.662324,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.921971543060849, 1.315041192...",NaN,NaN,EBMSNGAN32
19,EBM_Diff,8,92.86,0.005942,0.915449,narcissus8-ebm50diffmcmc150,2024_02_23_22_18,4937.661106,0.013974,0.865977,0.038094,0.746655,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8547375851579944, 1.37434575...",NaN,NaN,EBMSNGAN32
20,EBM_Diff,7,92.92,0.005722,0.922447,narcissus8-ebm50diffmcmc150,2024_02_24_00_53,5456.024278,0.010013,0.882482,0.019146,0.786686,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8425252318687146, 1.36552422...",NaN,NaN,EBMSNGAN32
21,EBM_Diff,3,92.58,0.022447,0.929621,narcissus8-ebm50diffmcmc150,2024_02_24_00_53,5455.743090,0.038314,0.896545,0.077971,0.820599,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9638536211169895, 1.49529515...",NaN,NaN,EBMSNGAN32
22,EBM_Diff,6,93.00,0.020731,0.902047,narcissus8-ebm50diffmcmc150,2024_02_24_00_53,5456.359715,0.185563,0.694960,0.398173,0.398790,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8487478101344974, 1.33852960...",NaN,NaN,EBMSNGAN32
23,EBM_Diff,5,92.91,0.020599,0.924736,narcissus8-ebm50diffmcmc150,2024_02_24_00_53,5455.712113,0.027993,0.892562,0.036004,0.819014,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8366300065804015, 1.34644612...",NaN,NaN,EBMSNGAN32
24,EBM_Diff,4,92.89,0.014767,0.917496,narcissus8-ebm50diffmcmc150,2024_02_24_00_53,5455.241441,0.054247,0.831118,0.079599,0.673526,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [2.018910096734381, 1.532504257...",NaN,NaN,EBMSNGAN32
25,EBM_Diff,1,93.17,0.004732,0.916725,narcissus8-ebm50diffmcmc150,2024_02_24_00_53,5456.052898,0.018530,0.835299,0.102839,0.623173,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.89490354091615, 1.3626803205...",NaN,NaN,EBMSNGAN32
26,EBM_Diff,2,92.81,0.013094,0.924648,narcissus8-ebm50diffmcmc150,2024_02_24_00_53,5456.701621,0.041637,0.869982,0.109947,0.736796,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9972917542738073, 1.37755700...",NaN,NaN,EBMSNGAN32
27,EBM_Diff,0,92.84,0.012016,0.915911,narcissus8-ebm50diffmcmc150,2024_02_24_00_53,5417.100479,0.020731,0.858187,0.046369,0.745268,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8386547544118388, 1.24370681...",NaN,NaN,EBMSNGAN32
28,EBM_Diff,9,92.94,0.007152,0.912940,narcissus8-ebm50diffmcmc150,2024_02_24_06_44,4966.821768,0.033671,0.832328,0.151342,0.628719,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.858363190880212, 1.345979394...",NaN,NaN,EBMSNGAN32
29,EBM_Diff,8,92.72,0.005722,0.914481,narcissus8-ebm50diffmcmc150,2024_02_24_06_44,4889.897246,0.008803,0.864701,0.025088,0.731932,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9880699147958585, 1.46783672...",NaN,NaN,EBMSNGAN32
30,EBM_Diff,7,92.83,0.004423,0.921457,narcissus8-ebm50diffmcmc150,2024_02_24_12_24,5475.729819,0.009727,0.880480,0.019718,0.773526,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8554580952505322, 1.35407020...",NaN,NaN,EBMSNGAN32
31,EBM_Diff,3,93.07,0.024230,0.929511,narcissus8-ebm50diffmcmc150,2024_02_24_12_24,5499.858161,0.043046,0.888864,0.081360,0.803411,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9860511112700947, 1.39694722...",NaN,NaN,EBMSNGAN32
32,EBM_Diff,6,92.76,0.020357,0.901783,narcissus8-ebm50diffmcmc150,2024_02_24_12_24,5498.956949,0.182284,0.703917,0.429291,0.410123,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8903008440266484, 1.38697164...",NaN,NaN,EBMSNGAN32
33,EBM_Diff,5,93.04,0.021347,0.925660,narcissus8-ebm50diffmcmc150,2024_02_24_12_24,5506.076385,0.035321,0.887214,0.056448,0.809947,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8720242141762657, 1.38647507...",NaN,NaN,EBMSNGAN32
34,EBM_Diff,4,93.09,0.014987,0.918860,narcissus8-ebm50diffmcmc150,2024_02_24_12_24,5466.709702,0.048922,0.838160,0.092760,0.678763,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [2.0092138024547217, 1.47107454...",NaN,NaN,EBMSNGAN32
35,EBM_Diff,1,92.74,0.005172,0.912390,narcissus8-ebm50diffmcmc150,2024_02_24_12_24,5506.086682,0.016417,0.828587,0.100176,0.646699,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9361611284563303, 1.47490723...",NaN,NaN,EBMSNGAN32
36,EBM_Diff,2,92.82,0.014195,0.919850,narcissus8-ebm50diffmcmc150,2024_02_24_12_24,5506.012441,0.050638,0.859573,0.143706,0.701585,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.991872569179291, 1.482682193...",NaN,NaN,EBMSNGAN32
37,EBM_Diff,0,93.22,0.009463,0.919124,narcissus8-ebm50diffmcmc150,2024_02_24_12_24,5475.286842,0.021479,0.850594,0.051585,0.720092,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8509208345047348, 1.32011432...",NaN,NaN,EBMSNGAN32
38,EBM_Diff,9,92.99,0.007482,0.916461,narcissus8-ebm50diffmcmc150,2024_02_24_22_27,4965.086418,0.034881,0.819190,0.105568,0.631338,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.9603508780984318, 1.41638359...",NaN,NaN,EBMSNGAN32
39,EBM_Diff,8,92.90,0.006382,0.916241,narcissus8-ebm50diffmcmc150,2024_02_24_22_27,4860.378617,0.012874,0.858649,0.036356,0.730458,"{""remote_user"": ""alice"", ""config_file"": ""./Con...","{""train_loss"": [1.8822474653458656, 1.39325578...",NaN,NaN,EBMSNGAN32